[toolchain]

[features]
seeds = false
skip-lint = false

[programs."https://api.testnet.sonic.game/"]
trepa = "FoJrCqMUvKkMcb15Xa3wEFaUEXjN9Yp9aDhPhUXdSZLs"

[registry]
url = "https://api.testnet.sonic.game/"

[provider]
cluster = "https://api.testnet.sonic.game/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "ts-node migrations/initialize.ts"