[toolchain]

[features]
seeds = false
skip-lint = false

[programs."https://api.testnet.sonic.game/"]
trepa = "4Bosp31ZmBLwXbsgq4J7pvkDRvAfV57sk1D8WpUcanCU"

[registry]
url = "https://api.testnet.sonic.game/"

[provider]
cluster = "https://api.testnet.sonic.game/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "ts-node migrations/initialize.ts"
pool = "ts-node migrations/initPool.ts"
predict = "ts-node migrations/postPrediction.ts"
value = "ts-node migrations/getPredictionData.ts"
resolve = "ts-node migrations/resolvePool.ts"
claim = "ts-node migrations/claimReward.ts"
