[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
onchain_svm = "E1YMZpRon87eymaLF6kE6GettQS93WFxP1oGaLmrti5q"

[registry]
url = "https://api.testnet.sonic.game/"

[provider]
cluster = "https://api.testnet.sonic.game/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "ts-node migrations/initialize.ts"